#!/usr/bin/env node
// Packs a snarkjs Groth16-over-BN254 verification_key.json + proof.json + public.json into
// the native Soroban BN254 host-function byte layout (Ethereum-compatible uncompressed,
// big-endian), emitted as a Rust source file of `pub const [u8; N]` fixtures.
//
// Why this exists (T8): the Soroban verifiers in contracts-soroban/*_verifier now call
// env.crypto().bn254() natively (CAP-0074) instead of deserializing an Arkworks-canonical
// blob, so the "convert snarkjs output to the verifier's byte format" step is just fixed-width
// big-endian packing — no EC-point re-serialization library needed. See
// contracts-soroban/agent_credential_verifier/README.md for the point-encoding spec this
// implements:
//   G1 (64 bytes):  BE(x) || BE(y)
//   G2 (128 bytes): BE(x_c1) || BE(x_c0) || BE(y_c1) || BE(y_c0)   (imaginary component first)
//   Fr (32 bytes):  BE(value)
//
// Usage:
//   node pack-bn254.mjs <vkey.json> <proof.json> <public.json> <out.rs> [--module-doc "..."]

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

function be32(decimalString) {
  const n = BigInt(decimalString);
  if (n < 0n) throw new Error(`negative field element: ${decimalString}`);
  const hex = n.toString(16).padStart(64, "0");
  if (hex.length !== 64) throw new Error(`field element too large for 32 bytes: ${decimalString}`);
  return hex;
}

/** snarkjs G1 point: [x, y, z] decimal strings, z MUST be "1" (affine, not projective). */
function packG1(point) {
  const [x, y, z] = point;
  if (z !== "1") throw new Error(`expected affine G1 (z=1), got z=${z}`);
  return be32(x) + be32(y);
}

/**
 * snarkjs G2 point: [[c0_x, c1_x], [c0_y, c1_y], [1, 0]] — snarkjs orders each Fp2 coordinate
 * as [real, imaginary]. Soroban's Bn254G2Affine wants each Fp2 coordinate as
 * BE(imaginary) || BE(real) (imaginary component first — matches the bn256Pairing precompile
 * test-vector convention). Empirically confirmed against a real circuit-generated proof in
 * agent_credential_verifier's test suite (test::create_job_verifies_real_circuit_proof) —
 * flip PACK_G2_IMAG_FIRST below and re-run if a future soroban-sdk release changes this.
 */
const PACK_G2_IMAG_FIRST = true;
function packG2(point) {
  const [[c0x, c1x], [c0y, c1y], [z0, z1]] = point;
  if (z0 !== "1" || z1 !== "0") throw new Error(`expected affine G2 (z=[1,0]), got z=[${z0},${z1}]`);
  const x = PACK_G2_IMAG_FIRST ? be32(c1x) + be32(c0x) : be32(c0x) + be32(c1x);
  const y = PACK_G2_IMAG_FIRST ? be32(c1y) + be32(c0y) : be32(c0y) + be32(c1y);
  return x + y;
}

function hexToRustArray(hex, indent = "    ") {
  const bytes = hex.match(/.{1,2}/g).map((b) => `0x${b}`);
  const lines = [];
  for (let i = 0; i < bytes.length; i += 16) {
    lines.push(indent + bytes.slice(i, i + 16).join(", ") + ",");
  }
  return lines.join("\n");
}

function constArray(name, hex) {
  const len = hex.length / 2;
  return `pub const ${name}: [u8; ${len}] = [\n${hexToRustArray(hex)}\n];`;
}

function main() {
  const [vkeyPath, proofPath, publicPath, outPath] = process.argv.slice(2);
  if (!vkeyPath || !proofPath || !publicPath || !outPath) {
    console.error("usage: pack-bn254.mjs <vkey.json> <proof.json> <public.json> <out.rs>");
    process.exit(1);
  }

  const vkey = JSON.parse(readFileSync(vkeyPath, "utf8"));
  const proof = JSON.parse(readFileSync(proofPath, "utf8"));
  const publicSignals = JSON.parse(readFileSync(publicPath, "utf8"));

  if (vkey.protocol !== "groth16" || vkey.curve !== "bn128") {
    throw new Error(`expected groth16/bn128, got ${vkey.protocol}/${vkey.curve}`);
  }

  const alpha = packG1(vkey.vk_alpha_1);
  const beta = packG2(vkey.vk_beta_2);
  const gamma = packG2(vkey.vk_gamma_2);
  const delta = packG2(vkey.vk_delta_2);
  const ic = vkey.IC.map(packG1);

  const proofA = packG1(proof.pi_a);
  const proofB = packG2(proof.pi_b);
  const proofC = packG1(proof.pi_c);

  const inputs = publicSignals.map(be32);

  const out = [
    "// AUTO-GENERATED by circuits/scripts/pack-bn254.mjs from a real snarkjs Groth16 proof.",
    "// Do not hand-edit — regenerate via `make credential` (or `make repagg`) then re-run the",
    "// packer. Byte layout: contracts-soroban/agent_credential_verifier/README.md.",
    "",
    constArray("ALPHA", alpha),
    constArray("BETA", beta),
    constArray("GAMMA", gamma),
    constArray("DELTA", delta),
    `pub const IC: [[u8; 64]; ${ic.length}] = [`,
    ...ic.map((h) => `    [\n${hexToRustArray(h, "        ")}\n    ],`),
    "];",
    constArray("PROOF_A", proofA),
    constArray("PROOF_B", proofB),
    constArray("PROOF_C", proofC),
    `pub const PUBLIC_INPUTS: [[u8; 32]; ${inputs.length}] = [`,
    ...inputs.map((h) => `    [\n${hexToRustArray(h, "        ")}\n    ],`),
    "];",
    "",
  ].join("\n");

  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, out);
  console.log(`[pack-bn254] wrote ${outPath} (${ic.length} IC entries, ${inputs.length} public inputs)`);
}

main();
